version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "18:00"
      timezone: "Africa/Douala"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "18:00"
      timezone: "Africa/Douala"
    groups:
       dependencies:
          patterns: ["*"]