name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create service key file
        run: echo "${{ secrets.GCP_SERVICE_KEY }}" > gcp_service_key.json
      - name: Print service key file contents
        run: cat gcp_service_key.json
      - name: Deploy to Google App Engine
        run: |
          echo "${{ secrets.GCP_SERVICE_KEY }}" > gcp_service_key.json
          gcloud auth activate-service-account --key-file gcp_service_key.json
          gcloud config set project "${{ secrets.GCP_PROJECT_ID }}"
          gcloud app deploy app.yaml --quiet
