name: Deploy to AWS Beanstalk
on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    name: deploy-to-aws-beanstalk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Generate deployment package
        run: zip -r devfolio.zip . -x '*.git*'
      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          use_existing_version_if_available: true
          version_description: ${{github.SHA}}
          application_name: baimamboukar-devfolio
          environment_name: baimamboukar-devfolio-env
          #existing_bucket_name: "devfolio-deployment-bucket"
          version_label: "v1.0.0 - ${{github.SHA}}"
          region: us-west-2
          deployment_package: devfolio.zip
